import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'

export default tseslint.config(
  // Never lint build output, deps, generated code, or vendored assets.
  {
    ignores: [
      'dist/**',
      'dist-python/**',
      'build-python/**',
      'release/**',
      'node_modules/**',
      'src/assets/**',
      'src/api-types.ts', // generated by `npm run gen:types`
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // The whole point of adding this: statically catch the class of hooks bug
      // (conditional hooks / early returns before hooks) that caused React #300.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // TypeScript already reports undefined identifiers with better accuracy,
      // so the core rule only produces false positives here.
      'no-undef': 'off',
      // The codebase intentionally uses `catch {}` to swallow best-effort work.
      'no-empty': ['error', { allowEmptyCatch: true }],

      // Pragmatic settings for the current codebase — tighten over time.
      // `any` is used heavily today; warn rather than fail the whole lint run.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Node-context files: Vite config, build scripts, Electron main/preload.
  // These are CommonJS and legitimately use require()/module/__dirname.
  {
    files: ['*.config.{js,ts}', 'scripts/**/*.js', 'electron/**/*.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { ...globals.node },
    },
    rules: {
      'no-empty': ['error', { allowEmptyCatch: true }],
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
)
