# Morale type mapping from TEW9.mdb tblMorale RecordName → display name
# RecordName is the game's internal code, MoraleType is the numeric value used in saves

MORALE_RECORD_NAMES = {
    "beingleftoffashowx": "Being Left Off A Show",
    "bookingofamatchatx": "Booking Of A Match",
    "apreshowinteraction": "A Pre-Show Interaction",
    "signingofanotherworker": "Signing Of Another Worker",
    "beingstuckindevelopment": "Being Stuck In Development",
    "negativeincidentinvolvingself": "Negative Incident Involving Them",
    "firingofx": "Firing Of",
    "beingfired": "Being Fired",
    "abotchedturnatx": "A Botched Turn",
    "apoornewgimmick": "A Poor New Gimmick",
    "ssdaacsa": "Not Being Released",
    "bookingofanangleatx": "Booking Of An Angle",
    "negativepostshowspeechatx": "Negative Post-Show Speech",
    "causinganinjuryatx": "Causing An Injury",
    "negativeincidentinvolvingx": "Negative Incident Involving",
    "toxicbackstageatmosphereatx": "Toxic Backstage Atmosphere",
    "beingrefusedafullpayrise": "Being Refused A Full Pay Rise",
    "beingrefusedapayrise": "Being Refused A Pay Rise",
    "gettinginjuredviaabotchatx": "Getting Injured Via A Botch",
    "nearlygettinginjuredviabotchat": "Nearly Getting Injured Via A Botch",
    "beingturnedheelatx": "Being Turned Heel",
    "feelingisolatedbackstageatx": "Feeling Isolated Backstage",
    "beingribbed": "Being Ribbed",
    "aribonx": "A Rib On",
    "theirrecentbooking": "His Recent Booking",
    "beingscrewedoveratx": "Being Screwed Over",
    "thescrewjobonx": "The Screwjob On",
    "workingwithaninjuredopponentx": "Working With An Impaired",
    "beingdroppedasfigurehead": "Being Dropped As Figurehead",
    "pressureofbeingfigurehead": "The Pressure Of Being Figurehead",
    "blamedforaninjuryatx": "Blamed For An Injury",
    "smstorm": "Getting Into A Social Media Storm",
    "birthdayignoredatx": "Birthday Ignored",
    "removedbookingteam": "Being Removed From Booking Team",
    "refusedbookingteamspot": "Being Refused A Booking Team Place",
    "allyremovedfrombookingteam": "Ally Removed From Booking Team",
    "enemyaddedtobookingteam": "Enemy Added To Booking Team",
    "beingremovedfrominnercircle": "Being Removed From Inner Circle",
    "refusedaninnercirclespot": "Being Refused An Inner Circle Place",
    "allyremovedfrominnercircle": "Ally Removed From Inner Circle",
    "enemyaddedtoinnercircle": "Enemy Added To Inner Circle",
    "beingaskedtobecomeastooge": "Being Asked To Become A Stooge",
    "poortravelorganisation": "Poor Travel Organisation",
    "notbeingalockerroomleader": "Not Being A Locker Room Leader",
    "dealingwithanunhappymoraleofcr": "Dealing With An Unhappy Morale Officer",
    "dislikingpreshowtrainingenviro": "Disliking Pre-Show Training Environment",
    "dislikingthechoiceofseniorref": "Disliking The Choice Of Senior Referee",
    "dislikingchoiceofsenioragent": "Disliking The Choice Of Senior Road Agent",
    "dislikingchoiceofchiefenforcer": "Disliking The Choice Of Chief Enforcers",
    "hearinghurtfulbackstagerumours": "Hearing Hurtful Backstage Rumours",
    "dislikingchoiceofheadoftalentr": "Disliking The Choice Of Head Of Talent Relations",
    "anunsuccessfulstorylineidea": "An Unsuccessful Storyline Idea",
    "anunsuccessfulcharacteridea": "An Unsuccessful Character Idea",
    "dislikingchoiceofbookingteam": "Disliking The Choice Of Booking Team",
    "dislikingmediascrumresponse": "Disliking Media Scrum Response",
    "beingdroppedasfigureheadheir": "Being Dropped As Figurehead Heir",
    "notbeingthefigurehead": "Not Being The Figurehead",
    "beingrefusedfigureheadposition": "Being Refused The Figurehead Position",
    "avictoryatx": "A Victory",
    "Signingofx": "Signing Of",
    "Positiveincidentinvolvingself": "Positive Incident Involving Them",
    "Firingofxpos": "Firing Of",
    "signinganewcontract": "Signing A New Contract",
    "asuccessfulturnatx": "A Successful Turn",
    "successfulgimmickchangeatx": "A Successful Gimmick Change",
    "beinggiventimeoff": "Being Given Time Off",
    "abonus": "A Bonus",
    "positivebackstageenvironment": "Backstage Environment",
    "positivepostshowspeechatx": "Positive Post-Show Speech",
    "positiveincidentinvolvingx": "Positive Incident Involving",
    "apayrise": "A Pay Rise",
    "gettingtocleartheair": "Getting To Clear The Air",
    "beingribbedatxpos": "Being Ribbed",
    "aribonxpos": "A Rib On",
    "theirrecentbookingpos": "His Recent Booking",
    "beingcompanyfigurehead": "Being Company Figurehead",
    "joiningbookingteam": "Joining Booking Team",
    "allyjoiningbookingteam": "Ally Joining Booking Team",
    "enemyremovedfrombookingteam": "Enemy Removed From Booking Team",
    "joininginnercircle": "Joining Inner Circle",
    "allyjoininginnercircle": "Ally Joining Inner Circle",
    "enemyremovedfrominnercircle": "Enemy Removed From Inner Circle",
    "havinganinnercirclerole": "Having An Inner Circle Role",
    "asuccessfulstorylineidea": "A Successful Storyline Idea",
    "asuccessfulcharacteridea": "A Successful Character Idea",
    "likingmediascrumresponse": "Liking Media Scrum Response",
    "likingacharitabledonation": "Liking A Charitable Donation",
}

# Build the numeric mapping from the template database
# MoraleType values 1-58 for negative types
NEGATIVE_MORALE = {}

NEGATIVE_BY_RECORD = [
    ("beingleftoffashowx", 1),
    ("bookingofamatchatx", 2),
    ("apreshowinteraction", 3),
    ("signingofanotherworker", 4),
    ("beingstuckindevelopment", 5),
    ("negativeincidentinvolvingself", 6),
    ("firingofx", 7),
    ("beingfired", 8),
    ("abotchedturnatx", 9),
    ("apoornewgimmick", 10),
    ("ssdaacsa", 11),
    ("bookingofanangleatx", 12),
    ("negativepostshowspeechatx", 13),
    ("causinganinjuryatx", 14),
    ("negativeincidentinvolvingx", 15),
    ("toxicbackstageatmosphereatx", 16),
    ("beingrefusedafullpayrise", 17),
    ("beingrefusedapayrise", 18),
    ("gettinginjuredviaabotchatx", 19),
    ("nearlygettinginjuredviabotchat", 20),
    ("beingturnedheelatx", 21),
    ("feelingisolatedbackstageatx", 22),
    ("beingribbed", 23),
    ("aribonx", 24),
    ("theirrecentbooking", 25),
    ("beingscrewedoveratx", 26),
    ("thescrewjobonx", 27),
    ("workingwithaninjuredopponentx", 28),
    ("beingdroppedasfigurehead", 29),
    ("pressureofbeingfigurehead", 30),
    ("blamedforaninjuryatx", 31),
    ("smstorm", 32),
    ("birthdayignoredatx", 33),
    ("removedbookingteam", 34),
    ("refusedbookingteamspot", 35),
    ("allyremovedfrombookingteam", 36),
    ("enemyaddedtobookingteam", 37),
    ("beingremovedfrominnercircle", 38),
    ("refusedaninnercirclespot", 39),
    ("allyremovedfrominnercircle", 40),
    ("enemyaddedtoinnercircle", 41),
    ("beingaskedtobecomeastooge", 42),
    ("poortravelorganisation", 43),
    ("notbeingalockerroomleader", 44),
    ("dealingwithanunhappymoraleofcr", 45),
    ("dislikingpreshowtrainingenviro", 46),
    ("dislikingthechoiceofseniorref", 47),
    ("dislikingchoiceofsenioragent", 48),
    ("dislikingchoiceofchiefenforcer", 49),
    ("hearinghurtfulbackstagerumours", 50),
    ("dislikingchoiceofheadoftalentr", 51),
    ("anunsuccessfulstorylineidea", 52),
    ("anunsuccessfulcharacteridea", 53),
    ("dislikingchoiceofbookingteam", 54),
    ("dislikingmediascrumresponse", 55),
    ("beingdroppedasfigureheadheir", 56),
    ("notbeingthefigurehead", 57),
    ("beingrefusedfigureheadposition", 58),
]

for record, mtype in NEGATIVE_BY_RECORD:
    NEGATIVE_MORALE[mtype] = MORALE_RECORD_NAMES[record]

# Positive types from TEW9.mdb tblMorale
POSITIVE_BY_RECORD = [
    ("avictoryatx", 101),
    ("Signingofx", 102),
    ("Positiveincidentinvolvingself", 103),
    ("Firingofxpos", 104),
    ("signinganewcontract", 105),
    ("asuccessfulturnatx", 106),
    ("successfulgimmickchangeatx", 107),
    ("beinggiventimeoff", 108),
    ("abonus", 109),
    ("positivebackstageenvironment", 110),
    ("positivepostshowspeechatx", 111),
    ("positiveincidentinvolvingx", 112),
    ("apayrise", 113),
    ("gettingtocleartheair", 114),
    ("beingribbedatxpos", 115),
    ("aribonxpos", 116),
    ("theirrecentbookingpos", 117),
    ("beingcompanyfigurehead", 118),
    ("joiningbookingteam", 119),
    ("allyjoiningbookingteam", 120),
    ("enemyremovedfrombookingteam", 121),
    ("joininginnercircle", 122),
    ("allyjoininginnercircle", 123),
    ("enemyremovedfrominnercircle", 124),
    ("havinganinnercirclerole", 125),
    ("asuccessfulstorylineidea", 126),
    ("asuccessfulcharacteridea", 127),
    ("likingmediascrumresponse", 128),
    ("likingacharitabledonation", 129),
]

POSITIVE_MORALE = {}
for record, mtype in POSITIVE_BY_RECORD:
    POSITIVE_MORALE[mtype] = MORALE_RECORD_NAMES.get(record, record)

MORALE_NAMES = {**NEGATIVE_MORALE, **POSITIVE_MORALE}
